// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package rogerapp

type UserInfo struct {
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
}
